**Tutorial : 2 - Explore Pandas library to analyze  and manipulate data.**
>Description: Use Pandas library for data analysis and manipulation.

>Dataset: Sample CSV file

>Task: Load the dataset, perform data cleaning, manipulation (like sorting, filtering), and exploratory data analysis.

**1.Import numpy and pandas library.**

In [1]:
import numpy as np
import pandas as pd

**2.Define series with 3 elements.**

In [2]:
s1=pd.Series([1,2,3])
s1

0    1
1    2
2    3
dtype: int64

**3.Define a series with a custom index**

In [3]:
s2 = pd.Series([1,2,3],index=['a','b','c'])
s2

a    1
b    2
c    3
dtype: int64

**4.Fetch Series value and index.**

In [4]:
values = s2.values
values

array([1, 2, 3])

In [5]:
index = s2.index
index

Index(['a', 'b', 'c'], dtype='object')

**5.Create DataFrame from list of Dict**

In [6]:
data = [{'Name': 'Subodh', 'Marks': 28},
        {'Name': 'Ram', 'Marks':27},
        {'Name': 'Abdul', 'Marks': 26},
        {'Name': 'John', 'Marks': 28},]
data

[{'Name': 'Subodh', 'Marks': 28},
 {'Name': 'Ram', 'Marks': 27},
 {'Name': 'Abdul', 'Marks': 26},
 {'Name': 'John', 'Marks': 28}]

In [7]:
type(data)

list

In [8]:
f1=pd.DataFrame(data)
f1

     Name  Marks
0  Subodh     28
1     Ram     27
2   Abdul     26
3    John     28

In [9]:
type(f1)

pandas.core.frame.DataFrame

**6.Create sample excel file in your computer and upload it to drive. Read the excel file in colab.**

In [10]:
student = pd.read_excel('/content/drive/MyDrive/AIML/student.xlsx')

In [11]:
student

     Name  Roll No
0   Riya         1
1   Priya        2
2  Manish        3
3    Diya        4
4    Jiya        5

**7.Explore Kaggle: Your Machine Learning and Data Science Community and UCI Machine Learning Repository for a dataset. Search iris dataset and download.**

In [12]:
iris=pd.read_csv('/content/drive/MyDrive/AIML/Iris.csv')
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [13]:
iris.index

RangeIndex(start=0, stop=150, step=1)

In [14]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

**8.Read iris dataset from csv file format and findout no. of rows and columns.**

In [15]:
num_rows = iris.shape[0]
num_cols = iris.shape[1]

print(f"Number of rows: {num_rows}")
print(f"Number of columns: {num_cols}")

Number of rows: 150
Number of columns: 6

**9.Perform the following operation on the iris dataset.**
>(a)Fetch the first 5 and last 5 rows.

>(b)Find index.

>(c)Find column name and rename it with SepalLengthCm':'Sepal_Length','SepalWidthCm':'Sepal_Width','PetalLengthCm':'Petal_Length','PetalWidthCm':'Petal_Width'

>(d)replace "Iris-versicolor" with "versicolor", same way do for rest 2 categories.

>(e)Find Statistical description.

>(f)extract specific column.

>(g)add new column with condition.

>(h)drop added column.

>(i)select first row data.

>(j)select 51 to 55 rows

>(k)Apply conditional formatting.

>(l)print "virginica" with "Petal_Length" more than 6.

>(m)find duplicate values

>(n)Find basic information.

>(o)Find null value in dataset.

In [16]:
# First 5 rows
iris.head()

# Last 5 rows
iris.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [17]:
# Index find
iris.index

RangeIndex(start=0, stop=150, step=1)

In [18]:
# Rename Columnns
iris = iris.rename(columns={'SepalLengthCm': 'Sepal_Length', 'SepalWidthCm': 'Sepal_Width', 'PetalLengthCm': 'Petal_Length', 'PetalWidthCm': 'Petal_Width'})
iris.head()

   Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width      Species
0   1           5.1          3.5           1.4          0.2  Iris-setosa
1   2           4.9          3.0           1.4          0.2  Iris-setosa
2   3           4.7          3.2           1.3          0.2  Iris-setosa
3   4           4.6          3.1           1.5          0.2  Iris-setosa
4   5           5.0          3.6           1.4          0.2  Iris-setosa

In [19]:
# Replace categories in 'Species' columns
iris['Species'] = iris['Species'].str.replace('Iris-', '')
iris.head()

   Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

In [20]:
# Statistical description
iris.describe()

               Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width
count  150.000000    150.000000   150.000000    150.000000   150.000000
mean    75.500000      5.843333     3.054000      3.758667     1.198667
std     43.445368      0.828066     0.433594      1.764420     0.763161
min      1.000000      4.300000     2.000000      1.000000     0.100000
25%     38.250000      5.100000     2.800000      1.600000     0.300000
50%     75.500000      5.800000     3.000000      4.350000     1.300000
75%    112.750000      6.400000     3.300000      5.100000     1.800000
max    150.000000      7.900000     4.400000      6.900000     2.500000

In [21]:
iris

      Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [22]:
# Example: Extracting 'Sepal_Length' column
sepal_length_column = iris['Sepal_Length']
sepal_length_column

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: Sepal_Length, Length: 150, dtype: float64

In [23]:
# Example: Adding a column 'Sepal_Area'
iris['Sepal_Area'] = iris['Sepal_Length'] * iris['Sepal_Width']
iris.head()

,Id,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species,Sepal_Area
0,1,5.1,3.5,1.4,0.2,setosa,17.85
1,2,4.9,3.0,1.4,0.2,setosa,14.70
2,3,4.7,3.2,1.3,0.2,setosa,15.04
3,4,4.6,3.1,1.5,0.2,setosa,14.26
4,5,5.0,3.6,1.4,0.2,setosa,18.00

In [24]:
iris

,Id,Sepal_Length,Sepal_Width,Petal_Length,Petal_Width,Species,Sepal_Area
0,1,5.1,3.5,1.4,0.2,setosa,17.85
1,2,4.9,3.0,1.4,0.2,setosa,14.70
2,3,4.7,3.2,1.3,0.2,setosa,15.04
3,4,4.6,3.1,1.5,0.2,setosa,14.26
4,5,5.0,3.6,1.4,0.2,setosa,18.00
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,virginica,20.10
146,147,6.3,2.5,5.0,1.9,virginica,15.75
147,148,6.5,3.0,5.2,2.0,virginica,19.50
148,149,6.2,3.4,5.4,2.3,virginica,21.08
149,150,5.9,3.0,5.1,1.8,virginica,17.70

In [25]:
# Drop added column
iris = iris.drop(columns=['Sepal_Area'])
iris.head()

   Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width Species
0   1           5.1          3.5           1.4          0.2  setosa
1   2           4.9          3.0           1.4          0.2  setosa
2   3           4.7          3.2           1.3          0.2  setosa
3   4           4.6          3.1           1.5          0.2  setosa
4   5           5.0          3.6           1.4          0.2  setosa

In [26]:
iris

      Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [27]:
# Select first row data
first_row = iris.iloc[0]
first_row

Id                   1
Sepal_Length       5.1
Sepal_Width        3.5
Petal_Length       1.4
Petal_Width        0.2
Species         setosa
Name: 0, dtype: object

In [28]:
# Select rows 51 to 55
iris.iloc[50:55]

    Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
50  51           7.0          3.2           4.7          1.4  versicolor
51  52           6.4          3.2           4.5          1.5  versicolor
52  53           6.9          3.1           4.9          1.5  versicolor
53  54           5.5          2.3           4.0          1.3  versicolor
54  55           6.5          2.8           4.6          1.5  versicolor

In [29]:
def highlight_petal_length(s):
    '''
    Highlight petal length greater than 6 for virginica species.
    '''
    is_virginica = s.Species == 'virginica'
    is_long_petal = s.Petal_Length > 6
    return ['background-color: yellow' if is_virginica and is_long_petal else '' for v in s]

styled_iris = iris.style.apply(highlight_petal_length, axis=1)  # Apply styling row-wise
styled_iris  # Display the styled DataFrame

In [30]:
iris

      Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [31]:
# Print "virginica" with "Petal_Length" more than 6:
iris[iris['Petal_Length']>5]

      Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width     Species
83    84           6.0          2.7           5.1          1.6  versicolor
100  101           6.3          3.3           6.0          2.5   virginica
101  102           5.8          2.7           5.1          1.9   virginica
102  103           7.1          3.0           5.9          2.1   virginica
103  104           6.3          2.9           5.6          1.8   virginica
104  105           6.5          3.0           5.8          2.2   virginica
105  106           7.6          3.0           6.6          2.1   virginica
107  108           7.3          2.9           6.3          1.8   virginica
108  109           6.7          2.5           5.8          1.8   virginica
109  110           7.2          3.6           6.1          2.5   virginica
110  111           6.5          3.2           5.1          2.0   virginica
111  112           6.4          2.7           5.3          1.9   virginica
112  113           6.8          3.0           5.5          2.1   virginica
114  115           5.8          2.8           5.1          2.4   virginica
115  116           6.4          3.2           5.3          2.3   virginica
116  117           6.5          3.0           5.5          1.8   virginica
117  118           7.7          3.8           6.7          2.2   virginica
118  119           7.7          2.6           6.9          2.3   virginica
120  121           6.9          3.2           5.7          2.3   virginica
122  123           7.7          2.8           6.7          2.0   virginica
124  125           6.7          3.3           5.7          2.1   virginica
125  126           7.2          3.2           6.0          1.8   virginica
128  129           6.4          2.8           5.6          2.1   virginica
129  130           7.2          3.0           5.8          1.6   virginica
130  131           7.4          2.8           6.1          1.9   virginica
131  132           7.9          3.8           6.4          2.0   virginica
132  133           6.4          2.8           5.6          2.2   virginica
133  134           6.3          2.8           5.1          1.5   virginica
134  135           6.1          2.6           5.6          1.4   virginica
135  136           7.7          3.0           6.1          2.3   virginica
136  137           6.3          3.4           5.6          2.4   virginica
137  138           6.4          3.1           5.5          1.8   virginica
139  140           6.9          3.1           5.4          2.1   virginica
140  141           6.7          3.1           5.6          2.4   virginica
141  142           6.9          3.1           5.1          2.3   virginica
142  143           5.8          2.7           5.1          1.9   virginica
143  144           6.8          3.2           5.9          2.3   virginica
144  145           6.7          3.3           5.7          2.5   virginica
145  146           6.7          3.0           5.2          2.3   virginica
147  148           6.5          3.0           5.2          2.0   virginica
148  149           6.2          3.4           5.4          2.3   virginica
149  150           5.9          3.0           5.1          1.8   virginica

In [32]:
iris

      Id  Sepal_Length  Sepal_Width  Petal_Length  Petal_Width    Species
0      1           5.1          3.5           1.4          0.2     setosa
1      2           4.9          3.0           1.4          0.2     setosa
2      3           4.7          3.2           1.3          0.2     setosa
3      4           4.6          3.1           1.5          0.2     setosa
4      5           5.0          3.6           1.4          0.2     setosa
..   ...           ...          ...           ...          ...        ...
145  146           6.7          3.0           5.2          2.3  virginica
146  147           6.3          2.5           5.0          1.9  virginica
147  148           6.5          3.0           5.2          2.0  virginica
148  149           6.2          3.4           5.4          2.3  virginica
149  150           5.9          3.0           5.1          1.8  virginica

[150 rows x 6 columns]

In [33]:
iris[iris['Species']=='setosa'].count()

Id              50
Sepal_Length    50
Sepal_Width     50
Petal_Length    50
Petal_Width     50
Species         50
dtype: int64

In [34]:
# Find duplicate values:
iris[iris.duplicated()]

Empty DataFrame
Columns: [Id, Sepal_Length, Sepal_Width, Petal_Length, Petal_Width, Species]
Index: []

In [35]:
iris.duplicated().sum()

0

In [36]:
# Find basic information:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            150 non-null    int64
 1   Sepal_Length  150 non-null    float64
 2   Sepal_Width   150 non-null    float64
 3   Petal_Length  150 non-null    float64
 4   Petal_Width   150 non-null    float64
 5   Species       150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [37]:
# Find null values in dataset:
iris.isna().sum()

Id              0
Sepal_Length    0
Sepal_Width     0
Petal_Length    0
Petal_Width     0
Species         0
dtype: int64

**10.Download student_info dataset. Find null value from it. And fill null value using mean of that column.**

Dataset Link: https://drive.google.com/drive/folders/1xTZizwH2onTZ8KpW1gttiFZ8SrY8RKOt?usp=sharing

In [38]:
student = pd.read_csv("/content/drive/MyDrive/AIML/student_info.csv")

In [39]:
student

     study_hours  student_marks
0           6.83          78.50
1           6.56          76.74
2            NaN          78.68
3           5.67          71.82
4           8.67          84.19
..           ...            ...
195         7.53          81.67
196         8.56          84.68
197         8.94          86.75
198         6.60          78.05
199         8.35          83.50

[200 rows x 2 columns]

In [40]:
student.head()

   study_hours  student_marks
0         6.83          78.50
1         6.56          76.74
2          NaN          78.68
3         5.67          71.82
4         8.67          84.19

In [41]:
student.isna()

     study_hours  student_marks
0          False          False
1          False          False
2           True          False
3          False          False
4          False          False
..           ...            ...
195        False          False
196        False          False
197        False          False
198        False          False
199        False          False

[200 rows x 2 columns]

In [42]:
student.isna().sum()

study_hours      5
student_marks    0
dtype: int64

In [43]:
student['study_hours'] = student['study_hours'].fillna(student['study_hours'].mean())

In [44]:
student.isna().sum()

study_hours      0
student_marks    0
dtype: int64

**11.Import adult data set from UCIML Adult - UCI Machine Learning Repository. And perform following task.**

>(a)Find missing value. Find type of missing data.

>(b)Handle missing value.

In [45]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in /usr/local/lib/python3.10/dist-packages (from ucimlrepo) (2024.12.14)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.0->ucimlrepo) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.17.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7

In [46]:
from ucimlrepo import fetch_ucirepo

# fetch dataset
adult = fetch_ucirepo(id=2)

# data (as pandas dataframes)
X = adult.data.features
y = adult.data.targets

# metadata
print(adult.metadata)

# variable information
print(adult.variables)

{'uci_id': 2, 'name': 'Adult', 'repository_url': 'https://archive.ics.uci.edu/dataset/2/adult', 'data_url': 'https://archive.ics.uci.edu/static/public/2/data.csv', 'abstract': 'Predict whether annual income of an individual exceeds $50K/yr based on census data. Also known as "Census Income" dataset. ', 'area': 'Social Science', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 48842, 'num_features': 14, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Income', 'Education Level', 'Other', 'Race', 'Sex'], 'target_col': ['income'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 1996, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5XW20', 'creators': ['Barry Becker', 'Ronny Kohavi'], 'intro_paper': None, 'additional_info': {'summary': "Extraction was done by Barry Becker from the 1994 Census database.  A set of reasonably clean records was extracted using the following conditions: ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))\n\nPrediction task is to determine whether a person's income is over $50,000 a year.\n", 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'Listing of attributes:\r\n\r\n>50K, <=50K.\r\n\r\nage: continuous.\r\nworkclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.\r\nfnlwgt: continuous.\r\neducation: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.\r\neducation-num: continuous.\r\nmarital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.\r\noccupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.\r\nrelationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.\r\nrace: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.\r\nsex: Female, Male.\r\ncapital-gain: continuous.\r\ncapital-loss: continuous.\r\nhours-per-week: continuous.\r\nnative-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.', 'citation': None}}
              name     role         type      demographic  \
0              age  Feature      Integer              Age
1        workclass  Feature  Categorical           Income
2           fnlwgt  Feature      Integer             None
3        education  Feature  Categorical  Education Level
4    education-num  Feature      Integer  Education Level
5   marital-status  Feature  Categorical            Other
6       occupation  Feature  Categorical            Other
7     relationship  Feature  Categorical            Other
8             race  Feature  Categorical             Race
9              sex  Feature       Binary              Sex
10    capital-gain  Feature      Integer             None
11    capital-loss  Feature      Integer             None
12  hours-per-week  Feature      Integer             None
13  native-country  Feature  Categorical            Other
14          income   Target       Binary           Income

                                          description units missing_values
0                                                 N/A  None             no
1   Private, Self-emp-not-inc, Self-emp-inc, Feder...  None            yes
2                                                None  None             no
3    Bachelors, Some-college, 11th, HS-grad, Prof-...  None             no
4                                                None  None             no
5   Married-civ-spouse, Divorced, Never-married, S...  None             no
6   Tech-support, Craft-repair, Other-service, Sal...  None            yes
7   Wife, Own-child, Husband, Not-in-family, Other...  None             no
8   White, Asian-Pac-Islander, Amer-Indian-Eskimo,...  None             no
9                                       Female, Male.  None             no
10                                               None  None             no
11                                               None  None             no
12                                               None  None             no
13  United-States, Cambodia, England, Puerto-Rico,...  None            yes
14                                       >50K, <=50K.  None             no

In [47]:
X

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States

In [48]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             48842 non-null  int64
 1   workclass       47879 non-null  object
 2   fnlwgt          48842 non-null  int64
 3   education       48842 non-null  object
 4   education-num   48842 non-null  int64
 5   marital-status  48842 non-null  object
 6   occupation      47876 non-null  object
 7   relationship    48842 non-null  object
 8   race            48842 non-null  object
 9   sex             48842 non-null  object
 10  capital-gain    48842 non-null  int64
 11  capital-loss    48842 non-null  int64
 12  hours-per-week  48842 non-null  int64
 13  native-country  48568 non-null  object
dtypes: int64(6), object(8)
memory usage: 5.2+ MB

In [49]:
X.isna().sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
marital-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
dtype: int64

In [50]:
X['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked',
       nan], dtype=object)

In [51]:
X['workclass'].mode()

0    Private
Name: workclass, dtype: object

In [52]:
X['workclass'].fillna(X['workclass'].mode()[0],inplace=True)

<ipython-input-52-c860d2db8f0c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['workclass'].fillna(X['workclass'].mode()[0],inplace=True)
<ipython-input-52-c860d2db8f0c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['workclass'].fillna(X['workclass'].mode()[0],inplace=True)

In [53]:
X['workclass'].unique()

array(['State-gov', 'Self-emp-not-inc', 'Private', 'Federal-gov',
       'Local-gov', '?', 'Self-emp-inc', 'Without-pay', 'Never-worked'],
      dtype=object)

In [54]:
X['occupation'].unique()

array(['Adm-clerical', 'Exec-managerial', 'Handlers-cleaners',
       'Prof-specialty', 'Other-service', 'Sales', 'Craft-repair',
       'Transport-moving', 'Farming-fishing', 'Machine-op-inspct',
       'Tech-support', '?', 'Protective-serv', 'Armed-Forces',
       'Priv-house-serv', nan], dtype=object)

In [55]:
X['occupation'].mode()

0    Prof-specialty
Name: occupation, dtype: object

In [56]:
X['occupation'].fillna(X['occupation'].mode()[0],inplace=True)

<ipython-input-56-376b107753a5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X['occupation'].fillna(X['occupation'].mode()[0],inplace=True)
<ipython-input-56-376b107753a5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['occupation'].fillna(X['occupation'].mode()[0],inplace=True)

In [57]:
X['workclass']

0               State-gov
1        Self-emp-not-inc
2                 Private
3                 Private
4                 Private
               ...
48837             Private
48838             Private
48839             Private
48840             Private
48841        Self-emp-inc
Name: workclass, Length: 48842, dtype: object

In [58]:
X.dropna(inplace=True)

<ipython-input-58-32f8c2353909>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.dropna(inplace=True)

In [59]:
X.isna().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
dtype: int64